version: "3"

vars:
  REPO_NAME: fantasim-world
  WORKTREE_BASE: ..

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # =============================================================================
  # Skills Management
  # =============================================================================

  sync-skills:
    desc: Sync skill stubs from .agent/skills to tool-specific directories
    aliases: [skills]
    cmds:
      - python scripts/sync_skills.py
    sources:
      - .agent/skills/**/SKILL.md
    generates:
      - .claude/skills/**/SKILL.md
      - .cline/skills/**/SKILL.md
      - .opencode/skills/**/SKILL.md
      - .windsurf/skills/**/SKILL.md

  sync-commands:
    desc: Sync command stubs from .agent/commands to .opencode/commands
    aliases: [commands]
    cmds:
      - python scripts/sync_commands.py
    sources:
      - .agent/commands/*.md
    generates:
      - .opencode/commands/*.md

  sync-opencode:
    desc: Generate .opencode from .agent (seed files + agents + commands + skills)
    cmds:
      - python scripts/sync_opencode.py

  # =============================================================================
  # Spec Kit Workflow
  # =============================================================================

  spec:init:
    desc: Initialize spec-kit in this repository
    cmds:
      - echo "Initializing spec-kit..."
      - specify init . --here --force --ai opencode --script ps --ignore-agent-tools
    status:
      - pwsh -NoProfile -Command 'if (Test-Path -LiteralPath ".specify") { exit 0 } else { exit 1 }'

  spec:new:
    desc: Create branch + worktree for new spec
    summary: |
      Creates a feature branch and git worktree for a new spec.

      Usage: task spec:new -- <feature-name>
      Example: task spec:new -- plate-merger

      This will create:
        - Branch: 001-<feature-name>
        - Worktree: ../{{.REPO_NAME}}--001-<feature-name>
        - Spec folder: specs/001-<feature-name>/
    cmds:
      - >-
        pwsh -NoProfile -File scripts/spec_worktree.ps1 -Mode new -Feature "{{.FEATURE}}" -CliArgs "{{.CLI_ARGS}}" -RepoName "{{.REPO_NAME}}" -WorktreeBase "{{.WORKTREE_BASE}}"

  spec:list:
    desc: List active spec worktrees
    cmds:
      - git worktree list

  spec:backfill:
    desc: Backfill an existing spec worktree with .specify/, .opencode/, and opencode.json if missing
    summary: |
      Copies spec-kit + OpenCode config into an existing worktree.

      Usage: task spec:backfill -- <feature-name>
    cmds:
      - >-
        pwsh -NoProfile -File scripts/spec_worktree.ps1 -Mode backfill -Feature "{{.FEATURE}}" -CliArgs "{{.CLI_ARGS}}" -RepoName "{{.REPO_NAME}}" -WorktreeBase "{{.WORKTREE_BASE}}"

  spec:specify:
    desc: Run specify phase for a feature
    summary: |
      Runs the Specify phase of spec-kit.

      Usage: task spec:specify FEATURE=<feature-name>

      Alternatively, use /speckit.specify in chat environments.
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:specify FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $tmpl = Join-Path $root ".specify/templates/spec-template.md"; $out = Join-Path $dir "spec.md"; if (Test-Path -LiteralPath $tmpl) { if (-not (Test-Path -LiteralPath $out)) { Copy-Item -Force $tmpl $out } } else { if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:plan:
    desc: Run plan phase for a feature
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:plan FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $tmpl = Join-Path $root ".specify/templates/plan-template.md"; $out = Join-Path $dir "plan.md"; if (Test-Path -LiteralPath $tmpl) { if (-not (Test-Path -LiteralPath $out)) { Copy-Item -Force $tmpl $out } } else { if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:tasks:
    desc: Run tasks phase for a feature
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:tasks FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $tmpl = Join-Path $root ".specify/templates/tasks-template.md"; $out = Join-Path $dir "tasks.md"; if (Test-Path -LiteralPath $tmpl) { if (-not (Test-Path -LiteralPath $out)) { Copy-Item -Force $tmpl $out } } else { if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:implement:
    desc: Run implement phase for a feature
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:implement FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $out = Join-Path $dir "IMPLEMENTATION.md"; if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:done:
    desc: Clean up worktree after spec is merged
    summary: |
      Removes a spec worktree after the PR has been merged.

      Usage: task spec:done -- <feature-name>

      Prerequisites:
        - All changes committed and pushed
        - PR merged to main
    cmds:
      - >-
        pwsh -NoProfile -File scripts/spec_worktree.ps1 -Mode done -Feature "{{.FEATURE}}" -CliArgs "{{.CLI_ARGS}}" -RepoName "{{.REPO_NAME}}" -WorktreeBase "{{.WORKTREE_BASE}}"
