version: "3"

vars:
  REPO_NAME: fantasim-world
  WORKTREE_BASE: ..

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  combine-cs:
    desc: "Combine all C# source files under project/ into scripts/combined_all_cs.cs"
    cmds:
      - python scripts/combine_cs.py
    silent: false

  combine-cs-no-tests:
    desc: "Combine C# source files excluding tests/"
    cmds:
      - python scripts/combine_cs.py --exclude-tests
    silent: false

  # =============================================================================
  # Smoke Host Verification
  # =============================================================================

  smoke:verify:
    desc: Build and run the plugin smoke host (fails if plugin ALC is not collectible)
    cmds:
      - dotnet build -c Release project/plugins/Geosphere.Plate.Runtime.Des/Geosphere.Plate.Runtime.Des.csproj
      - dotnet build -c Release project/hosts/Geosphere.Plate.PluginSmokeHost/Geosphere.Plate.PluginSmokeHost.csproj
      - dotnet run -c Release --project project/hosts/Geosphere.Plate.PluginSmokeHost/Geosphere.Plate.PluginSmokeHost.csproj

  smoke:verify:hotreload:
    desc: Same as smoke:verify but also runs ReloadPluginsAsync (set FANTASIM_SMOKEHOTRELOAD=1)
    cmds:
      - dotnet build -c Release project/plugins/Geosphere.Plate.Runtime.Des/Geosphere.Plate.Runtime.Des.csproj
      - dotnet build -c Release project/hosts/Geosphere.Plate.PluginSmokeHost/Geosphere.Plate.PluginSmokeHost.csproj
      - pwsh -NoProfile -Command '$env:FANTASIM_SMOKEHOTRELOAD="1"; dotnet run -c Release --project project/hosts/Geosphere.Plate.PluginSmokeHost/Geosphere.Plate.PluginSmokeHost.csproj'

  # =============================================================================
  # Agent Configuration Sync
  # =============================================================================

  agent:sync:
    desc: Sync all tool-specific directories from .agent
    aliases: [sync]
    cmds:
      - task: agent:sync-all

  agent:sync-all:
    desc: Sync all tool-specific directories from .agent
    cmds:
      - task: agent:sync:opencode
      - task: agent:sync:windsurf
      - task: agent:sync:claude
      - task: agent:sync:cline
      - task: agent:sync:kilocode
      - task: agent:sync:codex
      - task: agent:sync:cursor
      - task: agent:sync:gemini
      - task: agent:sync:roo

  agent:sync:opencode:
    desc: Sync OpenCode (.opencode + opencode.json) from .agent
    cmds:
      - python scripts/sync_opencode.py

  agent:sync:windsurf:
    desc: Sync Windsurf (.windsurf) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=windsurf
      - python scripts/sync_skills.py --skills --tools=windsurf
      - python scripts/sync_skills.py --commands --tools=windsurf

  agent:sync:claude:
    desc: Sync Claude Code (.claude + CLAUDE.md) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=claude
      - python scripts/sync_skills.py --skills --tools=claude

  agent:sync:cline:
    desc: Sync Cline (.clinerules + .cline) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=cline
      - python scripts/sync_skills.py --skills --tools=cline
      - python scripts/sync_skills.py --commands --tools=cline
      - python scripts/sync_skills.py --hooks --tools=cline

  agent:sync:kilocode:
    desc: Sync Kilo Code (.kilocode) from .agent
    cmds:
      - python scripts/sync_workflows.py
      - python scripts/sync_skills.py --rules --tools=kilocode
      - python scripts/sync_skills.py --skills --tools=kilocode

  agent:sync:codex:
    desc: Sync Codex (AGENTS.md + .codex) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=codex
      - python scripts/sync_skills.py --skills --tools=codex

  agent:sync:cursor:
    desc: Sync Cursor (.cursor) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=cursor
      - python scripts/sync_skills.py --skills --tools=cursor
      - python scripts/sync_skills.py --commands --tools=cursor

  agent:sync:gemini:
    desc: Sync Gemini (.gemini + GEMINI.md) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=gemini
      - python scripts/sync_skills.py --skills --tools=gemini
      - python scripts/sync_skills.py --commands --tools=gemini

  agent:sync:roo:
    desc: Sync Roo Code (.roo) from .agent
    cmds:
      - python scripts/sync_skills.py --rules --tools=roo
      - python scripts/sync_skills.py --skills --tools=roo
      - python scripts/sync_skills.py --commands --tools=roo

  agent:sync-skills:
    desc: Sync skill stubs from .agent/skills to tool-specific directories
    aliases: ["agent:skills"]
    cmds:
      - python scripts/sync_skills.py --skills
    sources:
      - .agent/skills/**/SKILL.md
    generates:
      - .claude/skills/**/SKILL.md
      - .cline/skills/**/SKILL.md
      - .kilocode/skills/**/SKILL.md
      - .opencode/skills/**/SKILL.md
      - .roo/skills/**/SKILL.md
      - .windsurf/skills/**/SKILL.md

  agent:sync-commands:
    desc: Sync command stubs from .agent/commands to .opencode/commands
    aliases: ["agent:commands"]
    cmds:
      - python scripts/sync_commands.py
    sources:
      - .agent/commands/*.md
    generates:
      - .opencode/commands/*.md

  agent:sync-workflows:
    desc: Sync workflows from .agent/workflows to tool-specific directories
    aliases: ["agent:workflows"]
    cmds:
      - python scripts/sync_workflows.py
    sources:
      - .agent/workflows/*.md
      - .agent/adapters/*/workflows/*.md
    generates:
      - .kilocode/workflows/*.md

  agent:sync-rules:
    desc: Sync rules from .agent/rules to tool-specific directories and AGENTS.md/CLAUDE.md
    aliases: ["agent:rules"]
    cmds:
      - python scripts/sync_rules.py
    sources:
      - .agent/rules/*.md
      - .agent/adapters/*/rules/*.md
    generates:
      - .kilocode/rules/*.md
      - .roo/rules/*.md
      - .windsurf/rules/*.md
      - .cline/rules/*.md
      - .cursor/rules/*.mdc
      - CLAUDE.md
      - AGENTS.md

  agent:sync-kilocode:
    desc: Generate .kilocode from .agent (skills + workflows + rules)
    aliases: ["agent:kilocode"]
    cmds:
      - python scripts/sync_kilocode.py

  agent:sync-opencode:
    desc: Generate .opencode from .agent (seed files + agents + commands + skills)
    aliases: ["agent:opencode"]
    cmds:
      - python scripts/sync_opencode.py

  # =============================================================================
  # Spec Kit Workflow
  # =============================================================================

  spec:init:
    desc: Initialize spec-kit in this repository
    cmds:
      - echo "Initializing spec-kit..."
      - specify init . --here --force --ai opencode --script ps --ignore-agent-tools
    status:
      - pwsh -NoProfile -Command 'if (Test-Path -LiteralPath ".specify") { exit 0 } else { exit 1 }'

  spec:new:
    desc: Create branch + worktree for new spec
    summary: |
      Creates a feature branch and git worktree for a new spec.

      Usage: task spec:new -- <feature-name>
      Example: task spec:new -- plate-merger

      This will create:
        - Branch: 001-<feature-name>
        - Worktree: ../{{.REPO_NAME}}--001-<feature-name>
        - Spec folder: specs/001-<feature-name>/
    cmds:
      - >-
        pwsh -NoProfile -File scripts/spec_worktree.ps1 -Mode new -Feature "{{.FEATURE}}" -CliArgs "{{.CLI_ARGS}}" -RepoName "{{.REPO_NAME}}" -WorktreeBase "{{.WORKTREE_BASE}}"

  spec:list:
    desc: List active spec worktrees
    cmds:
      - git worktree list

  spec:backfill:
    desc: Backfill an existing spec worktree with .specify/, .opencode/, and opencode.json if missing
    summary: |
      Copies spec-kit + OpenCode config into an existing worktree.

      Usage: task spec:backfill -- <feature-name>
    cmds:
      - >-
        pwsh -NoProfile -File scripts/spec_worktree.ps1 -Mode backfill -Feature "{{.FEATURE}}" -CliArgs "{{.CLI_ARGS}}" -RepoName "{{.REPO_NAME}}" -WorktreeBase "{{.WORKTREE_BASE}}"

  spec:specify:
    desc: Run specify phase for a feature
    summary: |
      Runs the Specify phase of spec-kit.

      Usage: task spec:specify FEATURE=<feature-name>

      Alternatively, use /speckit.specify in chat environments.
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:specify FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $tmpl = Join-Path $root ".specify/templates/spec-template.md"; $out = Join-Path $dir "spec.md"; if (Test-Path -LiteralPath $tmpl) { if (-not (Test-Path -LiteralPath $out)) { Copy-Item -Force $tmpl $out } } else { if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:plan:
    desc: Run plan phase for a feature
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:plan FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $tmpl = Join-Path $root ".specify/templates/plan-template.md"; $out = Join-Path $dir "plan.md"; if (Test-Path -LiteralPath $tmpl) { if (-not (Test-Path -LiteralPath $out)) { Copy-Item -Force $tmpl $out } } else { if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:tasks:
    desc: Run tasks phase for a feature
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:tasks FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $tmpl = Join-Path $root ".specify/templates/tasks-template.md"; $out = Join-Path $dir "tasks.md"; if (Test-Path -LiteralPath $tmpl) { if (-not (Test-Path -LiteralPath $out)) { Copy-Item -Force $tmpl $out } } else { if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:implement:
    desc: Run implement phase for a feature
    cmds:
      - >-
        pwsh -NoProfile -Command '& { $feature = "{{.FEATURE}}"; if ([string]::IsNullOrWhiteSpace($feature)) { throw "FEATURE variable required. Usage: task spec:implement FEATURE=<feature-name>" }; $root = (Get-Location).Path; $dir = Join-Path $root ("specs/" + $feature); New-Item -ItemType Directory -Force -Path $dir | Out-Null; $out = Join-Path $dir "IMPLEMENTATION.md"; if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType File -Force -Path $out | Out-Null } }'
    env:
      SPECIFY_FEATURE: "{{.FEATURE}}"

  spec:done:
    desc: Clean up worktree after spec is merged
    summary: |
      Removes a spec worktree after the PR has been merged.

      Usage: task spec:done -- <feature-name>

      Prerequisites:
        - All changes committed and pushed
        - PR merged to main
    cmds:
      - >-
        pwsh -NoProfile -File scripts/spec_worktree.ps1 -Mode done -Feature "{{.FEATURE}}" -CliArgs "{{.CLI_ARGS}}" -RepoName "{{.REPO_NAME}}" -WorktreeBase "{{.WORKTREE_BASE}}"

  # =============================================================================
  # Documentation Maintenance
  # =============================================================================

  docs:analyze-inbox:
    desc: Analyze docs/_inbox for duplicates and similar content
    summary: |
      Intelligently analyzes all files in docs/_inbox to find:
        - Exact duplicates (identical content)
        - Partial duplicates (similar content with shared sections)
        - Content similarity scores

      Generates detailed reports in docs/_inbox/_analysis/
    cmds:
      - python scripts/analyze_inbox_duplicates.py

  docs:analyze-inbox:threshold:
    desc: Analyze with custom similarity threshold
    summary: |
      Same as docs:analyze-inbox but with custom threshold.

      Usage: task docs:analyze-inbox:threshold THRESHOLD=0.5

      Threshold range: 0.0 (no similarity) to 1.0 (identical)
      Default: 0.3
    cmds:
      - python scripts/analyze_inbox_duplicates.py --threshold {{.THRESHOLD}}

  docs:merge-duplicates:
    desc: Intelligently merge files with partial duplication
    summary: |
      Smart merger that combines files with shared content:
        - Detects duplicate sections
        - Preserves unique content from each file
        - Creates consolidated documents
        - Removes redundant source files

      Default: merges files with ≥40% line overlap
      Run docs:analyze-inbox first to generate analysis.
    cmds:
      - python scripts/merge_duplicates.py

  docs:merge-duplicates:dry-run:
    desc: Preview merges without making changes
    cmds:
      - python scripts/merge_duplicates.py --dry-run

  docs:merge-duplicates:threshold:
    desc: Merge with custom overlap threshold
    summary: |
      Usage: task docs:merge-duplicates:threshold MIN_OVERLAP=0.6

      Threshold: minimum line overlap to trigger merge (0.0-1.0)
      - 0.4 (default): moderate overlap
      - 0.6: high overlap
      - 0.8: very high overlap
    cmds:
      - python scripts/merge_duplicates.py --min-overlap {{.MIN_OVERLAP}}

  docs:organize-inbox:
    desc: Organize docs/_inbox files into categorized subfolders
    summary: |
      Moves files in docs/_inbox root into subfolders:
        - conversation-exports/
        - discussions/
        - implementations/
        - refactoring/
        - integrations/
        - planning/
        - maintenance/

      Run AFTER docs:merge-duplicates for final organization.
    cmds:
      - python scripts/organize_inbox.py

  docs:organize-inbox:dry-run:
    desc: Preview inbox organization without moving files
    cmds:
      - python scripts/organize_inbox.py --dry-run
