using System.Collections.Immutable;
using FantaSim.Geosphere.Plate.SolverLab.Core.Corpus;
using FantaSim.Geosphere.Plate.SolverLab.Core.Models.PlateMotion;
using FantaSim.Geosphere.Plate.SolverLab.Core.Numerics;
using FantaSim.Geosphere.Plate.SolverLab.Core.Solvers.Reference;
using FantaSim.Geosphere.Plate.Topology.Contracts.Entities;
using MessagePack;

namespace FantaSim.Geosphere.Plate.SolverLabRunner;

public static class CorpusGenerator
{
    public static SolverCorpus GenerateSampleCorpus(MessagePackSerializerOptions options)
    {
        var cases = new List<CorpusCase>();

        // Case 1: Trivial - Single stationary plate, no forces
        cases.Add(CreateTrivialCase(options));

        // Case 2: Two Divergent Plates
        cases.Add(CreateDivergentCase(options));

        return new SolverCorpus
        {
            Domain = "PlateMotion",
            Version = "1.0",
            Cases = cases.ToArray()
        };
    }

    private static CorpusCase CreateTrivialCase(MessagePackSerializerOptions options)
    {
        var plateId = PlateId.NewId();
        var snapshot = new PlateTopologySnapshot
        {
            CurrentTimeS = 0,
            Plates = new[]
            {
                new PlateSnapshot
                {
                    PlateId = plateId,
                    Position = Vector3d.UnitX * 6371000, // Surface
                    Rotation = Quaterniond.Identity,
                    MassKg = 1e22,
                    AreaM2 = 1e12,
                    Type = PlateType.Oceanic
                }
            },
            Boundaries = Array.Empty<BoundarySnapshot>()
        };

        var input = new PlateMotionInput
        {
            Snapshot = snapshot,
            TimeDeltaS = 1.0f
        };

        // Expected: No motion
        var expectedResult = new PlateMotionResult
        {
            PlateMotions = new[]
            {
                new PlateMotion
                {
                    PlateId = plateId,
                    DeltaPosition = Vector3d.Zero,
                    DeltaRotation = Quaterniond.Identity,
                    Force = Vector3d.Zero,
                    Torque = Vector3d.Zero
                }
            },
            NewRifts = Array.Empty<RiftEvent>(),
            NewCollisions = Array.Empty<CollisionEvent>(),
            Metrics = new ComputationMetrics { ComputeTimeMs = 0, ConvergenceError = 0, IterationCount = 0 }
        };

        return new CorpusCase
        {
            CaseId = "case-001",
            Description = "Trivial stationary plate",
            Difficulty = CaseDifficulty.Trivial,
            Tags = new[] { "sanity" },
            InputData = MessagePackSerializer.Serialize(input, options),
            ExpectedOutput = MessagePackSerializer.Serialize(expectedResult, options)
        };
    }

    private static CorpusCase CreateDivergentCase(MessagePackSerializerOptions options)
    {
        var p1 = PlateId.NewId();
        var p2 = PlateId.NewId();
        var b1 = BoundaryId.NewId();

        var snapshot = new PlateTopologySnapshot
        {
            CurrentTimeS = 0,
            Plates = new[]
            {
                new PlateSnapshot
                {
                    PlateId = p1,
                    Position = Vector3d.UnitX * 6371000,
                    Rotation = Quaterniond.Identity,
                    MassKg = 1e22,
                    AreaM2 = 1e12,
                    Type = PlateType.Oceanic
                },
                new PlateSnapshot
                {
                    PlateId = p2,
                    Position = -Vector3d.UnitX * 6371000,
                    Rotation = Quaterniond.Identity,
                    MassKg = 1e22,
                    AreaM2 = 1e12,
                    Type = PlateType.Oceanic
                }
            },
            Boundaries = new[]
            {
                new BoundarySnapshot
                {
                    BoundaryId = b1,
                    PlateA = p1,
                    PlateB = p2,
                    Type = BoundaryType.Divergent,
                    SubductingPlate = default
                }
            }
        };

        var input = new PlateMotionInput
        {
            Snapshot = snapshot,
            TimeDeltaS = 1.0f
        };

        // Use Reference Solver to generate Ground Truth
        var solver = new ReferencePlateMotionSolver();
        var result = solver.Calculate(input);

        return new CorpusCase
        {
            CaseId = "case-002",
            Description = "Simple divergence (Generated by Reference Solver)",
            Difficulty = CaseDifficulty.Normal,
            Tags = new[] { "physics", "generated" },
            InputData = MessagePackSerializer.Serialize(input, options),
            ExpectedOutput = MessagePackSerializer.Serialize(result, options)
        };
    }
}
