#!/usr/bin/env pwsh
#requires -Version 7

<#
.SYNOPSIS
    Generates C# DTOs from JSON Schema files using QuickType.

.DESCRIPTION
    This script scans project/schemas/ for .schema.json files and generates
    corresponding C# DTO classes using QuickType.

.EXAMPLE
    ./scripts/generate-dtos.ps1
    Generates DTOs for all schemas.

.EXAMPLE
    ./scripts/generate-dtos.ps1 -Schema plates/dataset-manifest
    Generates DTO for a specific schema only.
#>

param(
    [string]$Schema = "*",
    [string]$OutputBase = "project/contracts",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$schemasDir = "project/schemas"
$quickTypeCmd = "npx"
$quickTypeArgs = @("quicktype")

# Verify schemas directory exists
if (-not (Test-Path $schemasDir)) {
    Write-Error "Schemas directory not found: $schemasDir"
    exit 1
}

# Find all schema files
$schemaFiles = Get-ChildItem -Path $schemasDir -Filter "*.schema.json" -Recurse

if ($schemaFiles.Count -eq 0) {
    Write-Host "No schema files found in $schemasDir"
    exit 0
}

Write-Host "Found $($schemaFiles.Count) schema file(s) to process..."
Write-Host ""

foreach ($file in $schemaFiles) {
    # Parse filename: dataset-manifest.schema.json -> dataset-manifest
    # Remove .schema.json extension
    $schemaName = $file.Name -replace "\.schema\.json$", ""

    # Skip if we couldn't determine a name
    if ([string]::IsNullOrWhiteSpace($schemaName)) {
        Write-Warning "Could not determine schema name for $($file.Name), skipping"
        continue
    }

    # Determine output path based on schema location
    $relativePath = $file.DirectoryName.Substring((Resolve-Path $schemasDir).Path.Length + 1)

    # Map schema paths to contract project names
    $contractProject = switch -Wildcard ($relativePath) {
        "plates*" { "Geosphere.Plate.Datasets.Contracts" }
        default { "Geosphere.Plate.Datasets.Contracts" }
    }

    $outputPath = Join-Path $OutputBase "$contractProject/Generated"
    $outputFile = Join-Path $outputPath "$schemaNameDto.cs"

    Write-Host "Processing: $($file.FullName)"
    Write-Host "  Output: $outputFile"

    if (-not $DryRun) {
        # Ensure output directory exists
        $fullOutputPath = Join-Path (Get-Location) $outputPath
        New-Item -ItemType Directory -Path $fullOutputPath -Force | Out-Null

        # Build QuickType arguments
        $qtArgs = @(
            "quicktype",
            "--lang", "csharp",
            "--src", $file.FullName,
            "--out", (Join-Path (Get-Location) $outputFile),
            "--namespace", "FantaSim.Geosphere.Plate.Datasets.Contracts.Generated",
            "--csharp-version", "9",
            "--type-style", "pascal",
            "--property-style", "pascal",
            "--use-system-text-json"
        )

        # Generate DTO using QuickType
        & $quickTypeCmd @qtArgs

        if ($LASTEXITCODE -ne 0) {
            Write-Error "QuickType failed for $($file.Name)"
            exit 1
        }

        # Add auto-generated header
        $fullOutputFile = Join-Path (Get-Location) $outputFile
        if (Test-Path $fullOutputFile) {
            $content = Get-Content $fullOutputFile -Raw
            $header = "// <auto-generated />`n// Generated by QuickType from $($file.Name)`n// DO NOT EDIT`n`n"
            $content = $header + $content
            Set-Content $fullOutputFile $content -NoNewline
            Write-Host "  Generated: $outputFile" -ForegroundColor Green
        }
    } else {
        Write-Host "  [DRY RUN] Would generate: $outputFile" -ForegroundColor Yellow
    }

    Write-Host ""
}

Write-Host "DTO generation complete!"
